Sorry: IndentationError: expected an indented block after 'for' statement on line 46 (track_race.py, line 47)
